Upgrade GoodJob gem
We were seeing the following error when attempting to enqueue emails
using GoodJob

    undefined method `broadcast' for ActiveSupport::Logger:Class (NoMethodError)
    logger.extend(ActiveSupport::Logger.broadcast(each_logger))

It looks like this was likely fixed in v3.19.3[1] of GoodJob so we've
decide to upgrade to the latest version.

After upgrading we ran

    rails generate good_job:update
    rails db:migrate

[1] https://github.com/bensheldon/good_job/blob/main/CHANGELOG.md#v3193-2023-09-28

Co-authored-by: Chris Roos <chris.roos@gofreerange.com>